[project]
name = "pybind_numpy_array_copy"
version = "0.0.1"
dependencies = ["numpy"]

[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.6.1"]
build-backend = "setuptools.build_meta"
